# Site settings
title: creVass.ORG
email: plumbers@creVass.ORG
description: A fount of multi-modal LLM knowledge has to begin somewhere ... creVass is our intelligence-gathering reverse-Pandoras-box sucker-upper for the SPRING of knowledge known as the DRAIN.tips AI inference engine for plumbing, electric, gas, water, sewer, construction, HVAC, IT infosec, utility infrastructure, landscaping and other homeowner questions.
twitter_username: creVassOrg
github_username:  creVassOrg

# Build settings
markdown: kramdown
