# Site settings
title: creVass.ORG
email: plumbers@creVass.ORG
description: The source of multi-modal engineering and patent knowledge for AI-enabled troubleshootering and redneck plumbering. 
twitter_username: creVassOrg
github_username:  creVassOrg

# Build settings
markdown: kramdown
