# Site settings
title: creVass.ORG
email: plumbers@creVass.ORG
description: Hybrid intelligence for plumbing / electric / HVAC / homelab.
twitter_username: DRAIN_tips
github_username:  creVass.ORG

# Build settings
markdown: kramdown
