# Site settings
title: creVass.ORG
email: plumbers@creVass.ORG
description: AI and intell for your battles with plumbing / electric and gas / HVAC / IT and infosec / water and sewer / utility infrastucture ... and pretty much any other reason to bend over.
twitter_username: creVassOrg
github_username:  creVassOrg

# Build settings
markdown: kramdown
