# Site settings
title: DRAIN.tips
email: bottom@drain.tips
description: An AI/ML exercise in gameplaying, like AlphaGo, except not as smelly.
twitter_username: DRAIN_tips
github_username:  DRAINtips

# Build settings
markdown: kramdown
