# Site settings
title: creVass.ORG
email: plumbers@creVass.ORG
description: creVass is our intelligence-gathering reverse-Pandoras-box sucker-upper for the DRAIN.tips AI inference engine for plumbing, electric, gas, water, sewer, construction, HVAC, IT infosec, utility infrastructure, landscaping and other homeowner questions.
twitter_username: creVassOrg
github_username:  creVassOrg

# Build settings
markdown: kramdown
